# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madlib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
