# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0003_field_parent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='madlib',
            name='id',
        ),
        migrations.AddField(
            model_name='madlib',
            name='created_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 14, 0, 24, 56, 292509, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='madlib',
            name='title',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
