# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0004_auto_20160814_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fill_in',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
